### PR TITLE
Fixes for path and portability issues with Benchy_Sump_LogicAnalyzer_Standalone example in DesignLab-1.0.8

### PR DESCRIPTION
**Pull request by skiphansen**
I think it's right this time.  
I'm a bit confused on how to install the DesignLab_Examples repository under DesignLab for development, any hints would be most welcome!

I'm working on a script to fix the reset of the .xise files automagically, but I'm still fumbling around with it.

Thanks again for the GREAT product!
Skip

### CODE REVIEW

**Comment by jackgassett** [comment]
Hmmm, too many unintentional changes to safely merge this pull request.

**Comment by skiphansen** [comment]
Thanks for looking Jack.  

Could you give me an example of an unintentional change and I'll take a look.  I did notice that my test builds modified the schematic files, but other than that I'm not aware of any unintentional changes.

Skip

**Comment by jackgassett** [comment]
Hey Skip,

When I look at all of the changed files in the pull request there are 40 files that are changed. There are bit files that are changed and xise files.

When I look at the changes in the xise files I see that there is an extra depth added to the directory...
../../libraries vs ../../../libraries

There shouldn't be any changes to the bit files and the changes to the xise files seem to be off at first glance...

**Comment by jackgassett** [comment]
I very much appreciate the pull request, but we have to be careful to not break anything under Windows... The changes we need to make should be just a couple small changes to a couple of files.

I created a new Gitter chat room here:
https://gitter.im/GadgetFactory/DesignLab_Examples

**Comment by jackgassett** [comment]
Hello Skip, I think I understand what the problem is that you are seeing. Please come into the Gitter chat room if you get a chance so we can have a discussion to confirm.
https://gitter.im/GadgetFactory/DesignLab_Examples
Jack.

**Comment by skiphansen** [comment]
Thanks for the help Jack, I now understand why none of these changes were needed!

**Pull request closed without merging**
